#pragma once



enum Direction {
	DIRECTION_AUCUNE	  =0x0,
	DIRECTION_HAUT		  =0x1,
	DIRECTION_DROITE      =0x2,
	DIRECTION_BAS         =0x4,
	DIRECTION_GAUCHE      =0x8,

	DIRECTION_HAUT_DROITE =0x3,
	DIRECTION_DROITE_BAS  =0x6,
	DIRECTION_BAS_GAUCHE  =0xC,
	DIRECTION_GAUCHE_HAUT =0x9,
	
	DIRECTION_TOUTES      =0xF
};